import hashlib

# Define the target MD5 hash
target_hash = "5f04609c04b031b6ed03b9d200e6cb5c"  # Replace with your target hash

# Define the list of inputs
inputs = [
    "Marielyst",
    "Løkken",
    "Hirtshals",
    "Sæby",
    "Grenaa",
    "Ebeltoft",
    "Kerteminde",
    "Nyborg",
    "Svendborg",
    "Faaborg",
    "Assens",
    "Middelfart",
    "Bogense",
    "Nakskov",
    "Nykøbing Falster",
    "Rødby",
    "Stege",
    "Præstø",
    "Vordingborg",
    "Køge",
    "Helsingør",
    "Hundested",
    "Frederikshavn",
    "Aalborg",
    "Esbjerg",
    "Ribe",
    "Sønderborg",
    "Aabenraa",
    "Haderslev",
    "Kolding",
    "Fredericia",
    "Vejle",
    "Horsens",
    "Aarhus",
    "Randers",
    "Hobro",
    "Mariager",
    "Skive",
    "Nykøbing Mors",
    "Thisted",
    "Hanstholm",
    "Lemvig",
    "Thyborøn",
    "Struer",
    "Holstebro",
    "Ringkøbing",
    "Hvide Sande",
    "Nymindegab",
    "Bork Havn",
    "Henne Strand",
    "Vejers Strand",
    "Fanø",
    "Rømø",
    "Mandø",
    "Møgeltønder",
    "Højer",
    "Ballum",
    "Bredebro",
    "Skærbæk",
    "Bramming",
    "Varde",
    "Oksbøl",
    "Vejle",
    "Juelsminde",
    "Bogense",
    "Otterup",
    "Kerteminde",
    "Nyborg",
    "Svendborg",
    "Rudkøbing",
    "Marstal",
    "Ærøskøbing",
    "Faaborg",
    "Assens",
    "Middelfart",
    "Fredericia",
    "Kolding",
    "Haderslev",
    "Aabenraa",
    "Sønderborg",
    "Gråsten",
    "Nordborg",
    "Augustenborg",
    "Tønder",
    "Højer",
    "Skærbæk",
    "Bredebro",
    "Løgumkloster",
    "Aabenraa",
    "Rødekro",
    "Padborg",
    "Kruså",
    "Sønderborg",
    "Nordborg",
    "Augustenborg",
    "Gråsten",
    "Broager",
    "Sønderborg",
    "Svendborg",
    "Rudkøbing",
    "Marstal",
    "Ærøskøbing",
    "Faaborg",
    "Assens",
    "Middelfart",
    "Bogense",
    "Otterup",
    "Kerteminde",
    "Nyborg",
    "Svendborg",
    "Rudkøbing",
    "Marstal",
    "Ærøskøbing",
    "Faaborg",
    "Assens",
    "Middelfart",
    "Fredericia",
    "Kolding",
    "Haderslev",
    "Aabenraa",
    "Sønderborg",
    "Gråsten",
    "Nordborg",
    "Augustenborg",
    "Tønder",
    "Højer",
    "Skærbæk",
    "Bredebro",
    "Løgumkloster",
    "Aabenraa",
    "Rødekro",
    "Padborg",
    "Kruså",
    "Sønderborg",
    "Nordborg",
    "Augustenborg",
    "Gråsten",
    "Broager",
    "Sønderborg",
    "Amager Strand",
    "Balka Strand",
    "Bisnap Strand",
    "Dueodde",
    "Fanø Bad",
    "Gudmindrup Strand",
    "Hornbæk Strand",
    "Marielyst Strand",
    "Råbylille Strand",
    "Skagen Strand",
    "Skallerup Klit",
    "Smørmosen Strand",
    "Vesterø Strand",
    "Zealand",
    "Funen",
    "Lolland",
    "Falster",
    "Bornholm",
    "Langeland",
    "Møn",
    "Als",
    "Samsø",
    "Ærø",
    "Læsø",
    "Anholt",
    "Fanø",
    "Tåsinge",
    "Amager",
    "Rømø",
    "Fejø",
    "Fur",
    "Orø",
    "Sejerø",
    "Tunø",
    "Endelave",
    "Drejø",
    "Hjarnø",
    "Omø",
    "Agersø",
    "Avernakø",
    "Bjørnø",
    "Egholm",
    "Hjortø",
    "Lyø",
    "Skarø",
    "Strynø",
    "Thurø",
    "Venø",
    "Aarø",
    "Alrø",
    "Barsø",
    "Bågø",
    "Egholm",
    "Gavnø",
    "Hesselø",
    "Kalvø",
    "Lindholm",
    "Masnedø",
    "Nekselø",
    "Ormø",
    "Saltholm",
    "Siø",
    "Slotsholmen",
    "Sprogø",
    "Vejrø",
    "Vigø",
    "Vorsø",
    "Æbelø",
        "København",
    "Aarhus",
    "Odense",
    "Aalborg",
    "Esbjerg",
    "Randers",
    "Kolding",
    "Horsens",
    "Vejle",
    "Roskilde",
    "Helsingør",
    "Næstved",
    "Fredericia",
    "Viborg",
    "Køge",
    "Holstebro",
    "Slagelse",
    "Hjørring",
    "Frederikshavn",
    "Sønderborg",
    "Svendborg",
    "Hillerød",
    "Thisted",
    "Kalundborg",
    "Nakskov",
    "Skagen",
    "Rønne",
    "Nexø",
    "Allinge",
    "Gudhjem",
    "Hasle",
    "Ærøskøbing",
    "Marstal",
    "Faaborg",
    "Nyborg",
    "Middelfart",
    "Bogense",
    "Assens",
    "Rudkøbing",
    "Lohals",
    "Tranekær",
    "Søby",
    "Nordborg",
    "Augustenborg",
    "Gråsten",
    "Aabenraa",
    "Haderslev",
    "Tønder",
    "Ribe",
    "Skærbæk",
    "Højer",
    "Fanø",
    "Rømø",
    "Samsø",
    "Anholt",
    "Læsø",
    "Sejerø",
    "Nekselø",
    "Tåsinge",
    "Thurø",
    "Møn",
    "Bogø",
    "Langeland",
    "Bornholm",
    "Christiansø",
    "Hirsholmene",
    "Egholm",
    "Fur",
    "Venø",
    "Mandø",
    "Hjarnø",
    "Tunø",
    "Endelave",
    "Agersø",
    "Omø",
    "Strynø",
    "Drejø",
    "Lyø",
    "Avernakø",
    "Fejø",
    "Femø",
    "Askø",
    "Glænø",
    "Orø",
    "Lindholm",
    "Holmen",
    "Skælskør",
    "Korsør",
    "Vordingborg",
    "Stege",
    "Præstø",
    "Kalvehave",
    "Gedser",
    "Nysted",
    "Sakskøbing",
    "Nakskov",
    "Stubbekøbing",
    "Grenaa",
    "Ebeltoft",
    "Juelsminde",
    "Hals",
    "Hou",
    "Frederiksværk",
    "Gilleleje",
    "Tisvildeleje",
    "Hundested",
    "Rørvig",
    "Nykøbing Sjælland",
    "Sjællands Odde",
    "Odsherred",
    "Vig",
    "Asnæs",
    "Kalvehave",
    "Bogø",
    "Sandvig",
    "Dueodde",
    "Snogebæk",
    "Svaneke",
    "Tejn",
    "Bølshavn",
    "Balka",
    "Årsdale",
    "Melsted",
    "Vang",
    "Klemensker",
    "Kås",
    "Østerlars",
    "Øster Marie",
    "Knudsker",
    "Rindby",
    "Sønderho",
    "Nordby",
    "Ballum",
    "Bredebro",
    "Visby",
    "Emmerlev",
    "Daler",
    "Løgumkloster",
    "Broager",
    "Vemmingbund",
    "Rendbjerg",
    "Sønderhav",
    "Kollund",
    "Kruså",
    "Padborg",
    "Egernsund",
    "Fynshav",
    "Mommark",
    "Skovby",
    "Høruphav",
    "Søby",
    "Ommel",
    "Ærøskøbing",
    "Rudkøbing",
    "Bagenkop",
    "Humble",
    "Tranekær",
    "Lohals",
    "Spodsbjerg",
    "Troense",
    "Valdemars Slot",
    "Svendborg",
    "Faaborg",
    "Lyø",
    "Avernakø",
    "Drejø",
    "Bjørnø",
    "Hjortø",
    "Skarø",
    "Strynø",
    "Ærø",
    "Bågø",
    "Assens",
    "Ebberup",
    "Glamsbjerg",
    "Kerteminde",
    "Langeskov",
    "Munkebo",
    "Nyborg",
    "Ringe",
    "Ørbæk",
    "Ullerslev",
    "Rudme",
    "Strib",
    "Middelfart",
    "Bogense",
    "Otterup",
    "Hasmark",
    "Tørresø",
    "Martofte",
    "Mesinge",
    "Hindsholm",
    "Langø",
    "Knudshoved",
    "Korshavn",
    "Gyldensteen Strand",
    "Lundeborg",
    "Hesselager",
    "Skårupøre",
    "Svanninge",
    "Vesterø",
    "Østerby",
    "Byrum",
    "Halskov",
    "Stigsnæs",
    "Agersø",
    "Omø",
    "Skælskør",
    "Korsør",
    "Sorø",
    "Gørlev",
    "Mullerup",
    "Reersø",
    "Sejerø",
    "Nekselø",
    "Havnsø",
    "Kalundborg",
    "Vesterlyng",
    "Holbæk",
    "Jyderup",
    "Rørvig",
    "Nørre Asmindrup",
    "Højby",
    "Vig Lyng",
    "Gudmindrup",
    "Klint",
    "Ordrup",
    "Kongsøre",
    "Ebeltoft",
    "Knebel",
    "Rønde",
    "Mols",
    "Helgenæs",
    "Grenaa",
    "Djursland",
    "Fjellerup",
    "Bønnerup",
    "Gjerrild",
    "Anholt",
    "Tunø",
    "Samsø",
    "Ballen",
    "Nordby (on Samsø)",
    "Kolby Kås",
    "Vesborg",
    "Rømø",
    "Lakolk",
    "Havneby",
    "Skærbæk",
    "Tønder",
    "Løgumgårde",
    "Højer",
    "Skibsted Fjord",
    "Rudbøl",
    "Havdrup",
    "Gudhjem",
    "Allinge",
    "Sandvig",
    "Nexø",
    "Åkirkeby",
    "Rønne",
    "Hasle",
    "Arnager",
    "Sandkås",
    "Tejn",
    "Klemensker",
    "Sorthat",
    "Nyker",
    "Pedersker",
    "Snogebæk",
    "Melsted",
    "Dueodde",
    "Balka",
    "Østermarie",
    "Almindingen",
    "Christiansø",
    "Frederiksø",
    "Hirsholmene",
    "Hirtshals",
    "Løkken",
    "Blokhus",
    "Slettestrand",
    "Thorup Strand",
    "Hanstholm",
    "Klitmøller",
    "Vorupør",
    "Stenbjerg",
    "Agger",
    "Thyborøn",
    "Lemvig",
    "Harboøre",
    "Bovbjerg",
    "Thorsminde",
    "Fjand",
    "Vedersø Klit",
    "Husby",
    "Hvide Sande",
    "Søndervig",
    "Ringkøbing",
    "Nymindegab",
    "Bork Havn",
    "Skjern Enge",
    "Esbjerg",
    "Fanø",
    "Sønderho",
    "Nordby (on Fanø)",
    "Blåvand",
    "Vejers Strand",
    "Grærup",
    "Henne Strand",
    "Nørre Nebel",
    "Bjerregård",
    "Fjaltring",
    "Hegnet",
    "Bovbjerg Fyr",
    "Skive",
    "Glyngøre",
    "Sallingsund",
    "Fur",
    "Mors",
    "Nykøbing Mors",
    "Sindbjerg",
    "Nørre Vorupør",
    "Doverodde",
    "Draget",
    "Ertebølle",
    "Livø",
    "Hvalpsund",
    "Trend",
    "Løgstør",
    "Aggersborg",
    "Frederikshavn",
    "Skagen",
    "Ålbæk",
    "Sæby",
    "Asaa",
    "Øster Hurup",
    "Hadsund",
    "Hobro",
    "Mariager",
    "Als Odde",
    "Egense",
    "Hals (by Limfjorden)",
    "Nibe",
    "Aalborg",
    "Svenstrup",
    "Støvring",
    "Arden",
    "Sebbersund",
    "Stinesminde",
    "Skagen",
    "Frederikshavn",
    "Læsø",
    "Ålbæk",
    "Dronninglund",
    "Tversted",
    "Løkken",
    "Blokhus",
    "Grønhøj",
    "Saltum",
    "Pandrup",
    "Hirtshals",
    "Børglum",
    "Hjørring",
    "Sæby",
    "Stokkemarke",
    "Knudshoved Odde",
    "Rødsand",
    "Møn",
    "Stege",
    "Klinteby",
    "Bogø",
    "Faxe",
    "Lolland",
    "Falster",
    "Nysted",
    "Bandholm",
    "Maribo",
    "Nakskov",
    "Søllested",
    "Vordingborg",
    "Faxe Ladeplads",
    "Eskilstrup",
    "Bisserup",
    "Kalvehave",
    "Stege",
    "Stubbekøbing",
    "Lilla Strand",
    "Fursund",
    "Hørsholm",
    "Rungsted Kyst",
    "Vedbæk",
    "Skodsborg",
    "Farum",
    "Hillerød",
    "Græsted",
    "Værløse",
    "Høsterkøb",
    "Nivå",
    "Nordsjælland",
    "Helsingør",
    "Gilleleje",
    "Tisvildeleje",
    "Hundested",
    "Rørvig",
    "Kystvejen",
    "Østerbro",
    "Hvidovre",
    "Amager",
    "Vesterbro",
    "Frederiksberg",
    "Sydhavnen",
    "Christianshavn",
    "Hellerup",
    "Klampenborg",
    "Skovlunde",
    "Solrød Strand",
    "Tårnby",
    "Køge",
    "Karrebæksminde",
    "Vallensbæk",
    "Greve Strand",
    "Rødovre",
    "Hedehusene",
    "Borup",
    "Glamsbjerg",
    "Nørre Nebel",
    "Kolding",
    "Vejle",
    "Middelfart",
    "Fredericia",
    "Billund",
    "Hedensted",
    "Horsens",
    "Givskud",
    "Grindsted",
    "Odder",
    "Skanderborg",
    "Tørring",
    "Brædstrup",
    "Give",
    "Ikast",
    "Herning",
    "Holstebro",
    "Lemvig",
    "Struer",
    "Nykøbing Mors",
    "Thisted",
    "Fjerritslev",
    "Aabybro",
    "Kerteminde",
    "Munkebo",
    "Nyborg",
    "Svendborg",
    "Rudkøbing",
    "Marstal",
    "Ærøskøbing",
    "Faaborg",
    "Assens",
    "Middelfart",
    "Bogense",
    "Otterup",
    "Hasmark",
    "Enebærodde",
    "Løgstør",
    "Ertebølle",
    "Gjøl",
    "Vilsund",
    "Sundby Mors",
    "Thisted",
    "Hurup",
    "Ydby",
    "Thyholm",
    "Boddum",
    "Jegindø",
    "Lemvig",
    "Struer",
    "Vinderup",
    "Holstebro",
    "Nissum Fjord",
    "Vestervig",
    "Helligsø",
    "Frøstrup",
    "Klim Strand",
    "Svinkløv",
    "Slettestrand",
    "Rødhus",
    "Brønderslev",
    "Dronninglund",
    "Hjallerup",
    "Øster Vrå",
    "Asnæs",
    "Sjællands Odde",
    "Havnebyen",
    "Ebeltoft",
    "Følle Strand",
    "Rolsø Bugt",
    "Mols Bjerge",
    "Kalø Vig",
    "Knebel Vig",
    "Langø",
    "Stenstrup",
    "Thurø",
    "Tåsinge",
    "Drejø",
    "Hjarnø",
    "Endelave",
    "Sejerø",
    "Samsø",
    "Tunø",
    "Anholt",
    "Læsø",
    "Fur",
    "Livø",
    "Agersø",
    "Omø",
    "Venø",
    "Fanø",
    "Mandø",
    "Rømø",
    "Strynø",
    "Bjørnø",
    "Skarø",
    "Avernakø",
    "Lyø",
    "Hjortø",
    "Glænø",
    "Hven (near Denmark)",
    "Hirsholmene",
    "Egholm",
    "Langli",
    "Alrø",
    "Barsø",
    "Ejer Bavnehøj",
    "Søby",
    "Hvide Sande",
    "Søndervig",
    "Blåvandshuk",
    "Bovbjerg Fyr",
    "Hanstholm",
    "Thyborøn Kanal",
    "Ferring",
    "Harboøre",
    "Lild Strand",
    "Bulbjerg",
    "Svinkløv Klitplantage",
    "Løkken",
    "Tornby",
    "Skallerup Klit",
    "Tversted",
    "Hirtshals",
    "Ålbæk",
    "Frederikshavn",
    "Skagen Odde",
    "Grenen",
    "Råbjerg Mile",
    "Lønstrup",
    "Rubjerg Knude",
    "Aalbæk Bugt",
    "Tannis Bugt",
    "Gilleleje",
    "Hornbæk",
    "Helsingør",
    "Humlebæk",
    "Nivå",
    "Rungsted",
    "Vedbæk",
    "Charlottenlund",
    "Dragør",
    "Kastrup",
    "Ishøj",
    "Hundige",
    "Karlslunde",
    "Køge",
    "Rødvig",
    "Faxe Ladeplads",
    "Præstø",
    "Vordingborg",
    "Nykøbing Falster",
    "Maribo",
    "Nakskov",
    "Sakskøbing",
    "Bandholm",
    "Guldborg",
    "Kragenæs",
    "Fejø",
    "Femø",
    "Askø",
    "Lilleø",
    "Langeland",
    "Rudkøbing",
    "Tranekær",
    "Bagenkop",
    "Spodsbjerg",
    "Lohals",
    "Dybbel",
    "Sønderborg",
    "Gråsten",
    "Aabenraa",
    "Haderslev"
]

# Function to calculate MD5 hash
def calculate_md5(input_string):
    return hashlib.md5(input_string.encode()).hexdigest()

# Iterate through inputs and find matches
for input_string in inputs:
    md5_hash = calculate_md5(input_string)
    if md5_hash == target_hash:
        print(f"Match found: Input '{input_string}' has hash '{md5_hash}'")
        break  # Stop on first match if needed
else:
    print("No matches found.")
