apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argocd-cert
  namespace: argocd
spec:
  secretName: argocd-tls
  issuerRef:
    name: homelab-ca
    kind: ClusterIssuer
  dnsNames:
    - argo.home.arpa
  privateKey:
    algorithm: RSA
    size: 2048
    rotationPolicy: Never
