apiVersion: apps/v1
kind: Deployment
metadata:
  name: filebrowser
  namespace: apps
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: filebrowser
  template:
    metadata:
      labels:
        app: filebrowser
    spec:
      containers:
        - name: filebrowser
          image: filebrowser/filebrowser:latest
          ports:
            - containerPort: 80
          args:
            - "--port=80"
            - "--root=/srv"
            - "--database=/database/filebrowser.db"
            - "--config=/config/settings.json"
          envFrom:
            - secretRef:
                name: filebrowser-auth
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: storage
              mountPath: /srv
            - name: data
              mountPath: /database
              subPath: database
            - name: data
              mountPath: /config
              subPath: config
      volumes:
        - name: storage
          hostPath:
            path: /data/storage/files
            type: Directory
        - name: data
          persistentVolumeClaim:
            claimName: filebrowser-data
