# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #FEE8CF
background         #302D32
cursor             #9A8888

active_tab_foreground     #302D32
active_tab_background     #FEE8CF
inactive_tab_foreground   #FEE8CF
inactive_tab_background   #302D32

active_border_color   #FEE8CF
inactive_border_color #302D32
bell_border_color     #291E31

color0      #555157
color1		#291E31
color2		#291E31
color3		#723439
color4		#733439
color5		#A94627
color6		#BC8D58
color7		#F5D5B2
color8		#AB957D
color9		#372841
color10		#372841
color11		#98454C
color12		#99454C
color13		#E15D34
color14		#FBBC76
color15		#F5D5B2
