# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #C0E7E3
background         #1B1B1E
cursor             #ADB2D8

active_tab_foreground     #1B1B1E
active_tab_background     #C0E7E3
inactive_tab_foreground   #C0E7E3
inactive_tab_background   #1B1B1E

active_border_color   #C0E7E3
inactive_border_color #1B1B1E
bell_border_color     #3B3C56

color0      #424144
color1		#3B3C56
color2		#735E99
color3		#785E96
color4		#A75B77
color5		#B8596B
color6		#388C83
color7		#9CD4CF
color8		#6D9491
color9		#4F5072
color10		#9A7ECC
color11		#A07EC8
color12		#DE799E
color13		#F5778F
color14		#4ABAAF
color15		#9CD4CF
