apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: appname-data
  namespace: apps
spec:
  storageClassName: local-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

