# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E2023)
$foreground = rgb(ECD0C2)
$color0 = rgb(444649)
$color1 = rgb(513E38)
$color2 = rgb(4C4441)
$color3 = rgb(5A4943)
$color4 = rgb(524B4A)
$color5 = rgb(63544C)
$color6 = rgb(975A3D)
$color7 = rgb(DCB3A0)
$color8 = rgb(9A7D70)
$color9 = rgb(6C534B)
$color10 = rgb(665B56)
$color11 = rgb(776259)
$color12 = rgb(6D6563)
$color13 = rgb(837066)
$color14 = rgb(CA7851)
$color15 = rgb(DCB3A0)
