# /* ---- 💫 https://github.com/LinuxBeginnings 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2F2728)
$foreground = rgb(F5F3EB)
$color0 = rgb(564C4D)
$color1 = rgb(634237)
$color2 = rgb(725043)
$color3 = rgb(7F6A5C)
$color4 = rgb(A6937A)
$color5 = rgb(A59F8E)
$color6 = rgb(AAA694)
$color7 = rgb(E9E6DA)
$color8 = rgb(A3A198)
$color9 = rgb(84574A)
$color10 = rgb(996B59)
$color11 = rgb(AA8D7B)
$color12 = rgb(DDC5A2)
$color13 = rgb(DDD4BD)
$color14 = rgb(E3DDC5)
$color15 = rgb(E9E6DA)
