apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-monitoring
  namespace: argocd
spec:
  project: homelab
  source:
    repoURL: https://github.com/droggokid/home-lab
    targetRevision: main
    path: cluster/monitoring
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: grafana-admin
      jsonPointers:
        - /data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
