apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: homelab-dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-data
